
/* challenge 12
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
the first 10 terms will be: 
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.
*/

vars
let amountOfNumbers = 40;
let numArray = [1,2];
let sum = 0;

function Fibonacci(amount){

    //loops and takes the index and previous number, adds them then adds that to the array
    for(i=0;i<amount;i++){
        let total = numArray[numArray.length-1] + numArray[numArray.length-2]
        numArray.push(total)
    }


    //sum of the even numbers
    sum = numArray.reduce(function(a,b){
        if(b % 2 == 0){
            return a + b;
        }else{
            return a;
        }
    });

}

Fibonacci(amountOfNumbers);
console.log(numArray);
console.log("sum: " + sum-1);
